### ISSUE TITLE
Pod depends on XCode 10 - swift 4.2

### ISSUE THREAD

**Issue by aleandro-coppola** [Yummypets/YPImagePicker#224]
How can I solve this?

```
YPImagePicker was resolved to 3.4.1, which depends on
      SteviaLayout (~> 4.2.0)
```

With Branch XCode10:
```
YPImagePicker (from `https://github.com/Yummypets/YPImagePicker`, branch `Xcode10`) was resolved to 3.4.1, which depends on
      PryntTrimmerView (~> 2.0)
```

But SteviaLayout 4.2.0 with swift 4.2 not working

XCode 10 - swift 4.2

**Comment by 5fcgdaeb** [comment]
Pretty much stuck here as well. I have tried the following combination and the pod installation fails with the PryntTrimmerView related error.

What I have tried:
```
pod 'SteviaLayout', :git => 'https://github.com/freshOS/Stevia.git', :tag => '4.4.0'
pod 'PryntTrimmerView', :git => 'https://github.com/HHK1/PryntTrimmerView.git', :tag => '3.0.0-beta.1'
pod 'YPImagePicker', :git => 'https://github.com/Yummypets/YPImagePicker.git', :branch => 'Xcode10'
```

Error:

```
[!] CocoaPods could not find compatible versions for pod "PryntTrimmerView":
  In snapshot (Podfile.lock):
    PryntTrimmerView (from `https://github.com/HHK1/PryntTrimmerView.git`, tag `3.0.0-beta.1`)

  In Podfile:
    PryntTrimmerView (from `https://github.com/HHK1/PryntTrimmerView.git`, tag `3.0.0-beta.1`)

    YPImagePicker (from `https://github.com/Yummypets/YPImagePicker.git`, branch `Xcode10`) was resolved to 3.4.1, which depends on
      PryntTrimmerView (~> 2.0)
```

**Comment by s4cha** [comment]
@Coppola-Aleandro @5fcgdaeb Sorry about that :/ This is being fixed in here: https://github.com/Yummypets/YPImagePicker/pull/222 will keep you posted as soon as it's fixed :)

**Comment by s4cha** [comment]
Hey, after some research, it looks like the last issue comes from our PryntTrimmerView dependency.
I opened an issue here https://github.com/HHK1/PryntTrimmerView/issues/37
to have this sorted.

As much as we all love new swift versions, it's always an extra workload for us to update all projects and make sure everything works fine. I'll do my best to solve that asap. Thanks a ton for being so patient 🙏

**Comment by s4cha** [comment]
In the meantime, Carthage integration is up in 3.5.0 https://github.com/Yummypets/YPImagePicker/releases/tag/3.5.0

**Comment by Zyoma108** [comment]
Any updates? When will version 3.5.0 be available with CocoaPods?

**Comment by aleandro-coppola** [comment]
I have no idea how it is possible, but also updating the operating system to Mojave, xCode 10, swift 4.2 also works with version 3.4

This is my Pod.lock:

`YPImagePicker (3.4.0)
PryntTrimmerView (~> 2.0)
SteviaLayout (~> 4.2.0)`

**Comment by s4cha** [comment]
@Coppola-Aleandro the mysteries of Cocoapods I guess xD

**Comment by s4cha** [comment]
@Coppola-Aleandro @5fcgdaeb @Zyoma108 
This should be fixed by now, 3.5.1 is available on Cocoapods "
https://github.com/Yummypets/YPImagePicker/releases/tag/3.5.1
http://cocoapods.org/pods/YPImagePicker

Let me know if that works,

Cheers!

**Comment by Zyoma108** [comment]
All is ok! Thanks!

**Comment by 5fcgdaeb** [comment]
Working well, thanks for the quick fix!

**Comment by s4cha** [comment]
@Coppola-Aleandro @Zyoma108 @5fcgdaeb Thanks for your patience 🙏  :)

**Comment by mohsinka** [comment]
Hi there, I updated the pods and am still getting some 33 errors. Although my Swift version is also set to 4.2, Mojave and have xCode 10. I don't know how to proceed, please help.

<img width="1440" alt="screen shot 2018-10-15 at 5 54 04 pm" src="https://user-images.githubusercontent.com/6949964/46952364-08768880-d0a4-11e8-96d6-e31b9a96a43a.png">

**Comment by jewell86** [comment]
@mohsinka I'm having the exact same issue, with 33 errors related to YPImagePicker. Tried everything, can't figure out a fix.

**Comment by ugenlik** [comment]
@mohsinka  and @jewell86 , Are you sure you use the correct build settings?

What's in your `Podfile.lock` ?

It should be like 

```
  - YPImagePicker (3.5.2):
    - PryntTrimmerView (~> 3.0.0)
    - SteviaLayout (~> 4.4.0)
```

if not , delete the podfile like from your folder and delete the pods folder too, let only Podfile be in your folder.

then run  `pod update` 

if that doesnt work it means your settings are not 4.2 either in your xcode or in your podfile.


You can try following at the end of your podfile 

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
   
    if  target.name == 'PryntTrimmerView' || target.name == 'SteviaLayout' || target.name == 'YPImagePicker'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end

 installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
```

**Comment by jewell86** [comment]
Thank you, I will try these things. YPImagePicker was working perfectly for
me until I updated to Xcode 10, and then it no longer worked (along with
some other things, I had a ton of issues to figure out and that was the
last one I was working on). I will let you know when I try it, and I really
appreciate your quick response, it is super helpful!!
Jewell

**Comment by ugenlik** [comment]
@jewell86  When I updated to Swift 4.2 I had a lot of problems too , it was because some frameworks still use swift 3 like Alamofire and Firebase, some of them use Swift 4.0 and some of them use Swift 4.2

You need to adjust your podfile's post installer for each target , like in my previous reply 

`config.build_settings['SWIFT_VERSION'] = '4.2'` 

It is a painful process to find what each project uses in terms of Swift Version, but you will figure it out eventually....

**Comment by jewell86** [comment]
Heh okay cool, thank you. I have learned Swift on my own and built my
project all on my own, so when this happened I had NO idea how to fix it! I
was actually going to an interview with an employer & couldn't get my app
to build because of the updates, it was pretty embarrassing! I think your
tips will help a lot, I'll try them out asap & seriously appreciate the
help!
