### ISSUE TITLE
How can I select multiple photos without selecting the first photo by default?

### ISSUE THREAD

**Issue by LuYinhao** [Yummypets/YPImagePicker#575]
How can I select multiple photos without selecting the first photo by default?

**Comment by NikKovIos** [comment]
Describe what you want more detail please.

**Comment by Ludotrico** [comment]
@LuYinhao @NikKovIos this is a feature that has been implemented, but does not work correctly.
Try:

        config.library.preSelectItemOnMultipleSelection = false
        config.library.defaultMultipleSelection = true

**Comment by LuYinhao** [comment]
> Describe what you want more detail please.

When I set it to multi-select, when I enter the album, the first image will be selected automatically. But I don't want that effect. I want to choose the pictures myself. Because the first picture is often not the one I want to pick.

**Comment by cclaflin89** [comment]
+1

**Comment by NikKovIos** [comment]
Fixed 3f9dedec7584e5381370a0576a5077d0dc0b34d8

**Comment by ibrahimzakarya** [comment]
I can't see the change when installing from cocoapods .... any thoughts 
<img width="902" alt="Screen Shot 2021-02-13 at 7 53 49 PM" src="https://user-images.githubusercontent.com/20393720/107854434-34050b80-6e35-11eb-8f2e-1a111ca42d8b.png">

**Comment by fukemy** [comment]
got same problem here even 
```
 config.library.preSelectItemOnMultipleSelection = false
    config.library.defaultMultipleSelection = true
```

**Comment by fukemy** [comment]
hi, i updated to version 4.4.0 but still see this line have only !multipleSelectionEnabled, can u double check it again @NikKovIos

**Comment by NikKovIos** [comment]
Check the last release 4.5.0
